export const FETCH_OFFERS = 'FETCH_OFFERS';
export const FETCH_OFFERS_SUCCES = 'FETCH_OFFERS_SUCCES';
export const FETCH_OFFERS_FAILED = 'FETCH_OFFERS_FAILED';
export const FETCH_OFFER_DETAILS = 'FETCH_OFFER_DETAILS';
export const FETCH_OFFER_DETAILS_SUCCES = 'FETCH_OFFER_DETAILS_SUCCES';
export const FETCH_OFFER_DETAILS_FAILED = 'FETCH_OFFER_DETAILS_FAILED';
export const SET_INITIALIZE = 'SET_INITIALIZE';
export const SET_PAGE_INDEX = 'SET_PAGE_INDEX';
